org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.59
loader_version_range=[21,)

## Mod Properties
mod_id=superb_warfare_expanded
mod_name=Superb Warfare Expanded
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.superb.warfare.expanded
